### ISSUE TITLE
TypeError:undefined is not object(evaluating 'React.PropTypes.func')

### ISSUE THREAD

**Issue by GTooo** [react-native-community/react-native-viewpager#100]
My dependencies:
"dependencies": {
    "@react-native-community/viewpager": "^2.0.1",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-native": "0.61.3",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-paper": "^3.1.1",
    "react-native-swiper": "^1.5.14",
    "react-native-tab-navigator": "^0.3.4",
    "react-native-vector-icons": "^6.6.0",
    "react-native-viewpager": "^0.2.13",
    "react-navigation": "^4.0.10",
    "react-navigation-material-bottom-tabs": "^2.1.5",
    "react-navigation-tabs": "^2.5.6"
  },

Integrated use framework prompt error, error content:

TypeError:undefined is not object(evaluating 'React.PropTypes.func')

<global>
D:\RN_Project\node_modules\react-native-viewpager\DefaultViewPageIndicator.js:51:30

I found in DefaultViewPageIndicator.js :

var DefaultViewPageIndicator = React.createClass({
  propTypes: {
    goToPage: React.PropTypes.func,
    activePage: React.PropTypes.number,
    pageCount: React.PropTypes.number
  },

Is this a problem? How to solve.

**Comment by troZee** [comment]
Are you sure, that you did not make a mistake ? I think this is another lib, because our project does not contain `DefaultViewPageIndicator` 

I close this due above reason.
