### ISSUE TITLE
initialPage is not working in Android?

### ISSUE THREAD

**Issue by srajesh02529** [react-native-community/react-native-viewpager#101]
initialPage={2}, this property is not working in android?always it loads the '0' position page.

**Comment by ferrannp** [comment]
@srajesh02529 mind sharing your code or reproducible example? I tried in our example and it works fine.

**Comment by srajesh02529** [comment]
<ViewPager
                        style={styles.viewpager}
                        initialPage={2}
                        onPageScroll={this.onPageScroll}
                        onPageSelected={this.onPageSelected}
                        pageMargin={10}
                        ref={viewPager => { this.viewPager = viewPager; }}>
                        { this.renderPage(page)}
                      
                    </ViewPager>

**Comment by ferrannp** [comment]
@srajesh02529 we need more. What you pasted seems ok and it works in our example. Can you make a repository that we can run?

**Comment by xiyunanhai1028** [comment]
you can set setPageWithoutAnimation in componentDidUpdate,like this:
componentDidUpdate(){
        this._viewPager.current!.setPageWithoutAnimation(videoindex)
    }

**Comment by alok-careerlabs** [comment]
@xiyunanhai1028 it worked perfectly for me! Thanks a lot for saving my day 👯‍♂️

**Comment by AmirDiafi** [comment]
> you can set setPageWithoutAnimation in componentDidUpdate,like this:
> componentDidUpdate(){
> this._viewPager.current!.setPageWithoutAnimation(videoindex)
> }

this makes bad performance, you should make a condition to check if the page has navigated or not yet.
`
this.has_navigatedthis = false
componentDidUpdate(){
    if(!this.has_navigatedthis && videoindex) {
        this.has_navigatedthis = true
        this._viewPager.current!.setPageWithoutAnimation(videoindex)
    }
 }`
