### ISSUE TITLE
API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.

### ISSUE THREAD

**Issue by Gark** [react-native-community/react-native-viewpager#105]
Android build log.

Configure project :react-native-screens
WARNING: API `variant.getJavaCompile()` is obsolete and has been replaced with `variant.getJavaCompileProvider()`
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: Called from: `../node_modules/react-native-screens/android/build.gradle:100`

v3.1.0

**Comment by troZee** [comment]
This issue refers to `react-native-screens`.
