### ISSUE TITLE
Disable bouncing on iOS

### ISSUE THREAD

**Issue by osdnk** [react-native-community/react-native-viewpager#106]
# Feature Request

https://stackoverflow.com/questions/34652666/no-bouncing-on-uipageviewcontroller

I would be nice to disable it sometimes

## Why it is needed

I need it in my app and I believe it's a good feature overall. 

## Possible implementation

https://stackoverflow.com/questions/34652666/no-bouncing-on-uipageviewcontroller

### Code sample

 ¯\\_(ツ)_/¯

**Comment by osdnk** [comment]
cc @wojtus7 @christianbaroni

**Comment by troZee** [comment]
Duplicated https://github.com/react-native-community/react-native-viewpager/issues/63

**Comment by osdnk** [comment]
sorry!
