### ISSUE TITLE
Overdrag prop does not work on IoS

### ISSUE THREAD

**Issue by panda0603** [react-native-community/react-native-viewpager#108]
In the document, there is overdrag property for Ios. 

However, when I check ViewPager props, there seem to be no overdrag property. 

Setting overdrag={false} does not work either for Ios. 

Is this a bug or not yet implemented feature?

I'm confused because in the document it exists

Thank you.

**Comment by ferrannp** [comment]
The PR https://github.com/react-native-community/react-native-viewpager/pull/107 was merged some hours ago and it has not been released yet. I'll do it during the day today.
