### ISSUE TITLE
Migration to ViewPager2

### ISSUE THREAD

**Issue by troZee** [react-native-community/react-native-viewpager#118]
# Feature Request

## Why it is needed
Earlier this year, Google announced ViewPager2 in Google IO/19. ViewPager2 is the replacement of ViewPager and is much better. The biggest change in the ViewPager2 API is that it now uses the RecyclerView.

## Possible implementation

```kotlin
class PagerAdapter : RecyclerView.Adapter<PageViewHolder>() {
    var list: List<ReactNativeView> = listOf()
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): PageViewHolder {
        return PageViewHolder(parent)
    }
override fun onBindViewHolder(holder: PageViewHolder, position: Int) {
        holder.bind(list[position])
    }
fun setItem(list: List<ReactNativeView>) {
        this.list = list
        notifyDataSetChanged()
    }
override fun getItemCount(): Int = list.size
}
```

**Comment by ferrannp** [comment]
I recommend playing and having fun with https://github.com/android/views-widgets-samples/tree/master/ViewPager2. See examples:

![ezgif-1-590bcacca31d](https://user-images.githubusercontent.com/774577/70046541-8bb7ae00-15c6-11ea-94bc-48cb5f48a5fd.gif)
![tabs](https://user-images.githubusercontent.com/774577/70046543-8bb7ae00-15c6-11ea-9f15-b0ab151b92c4.gif)

😄

**Comment by xfumihiro** [comment]
correct me if I'm wrong but since ViewPager2 is based on recyclerview and somehow they decided to make it [final](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:viewpager2/viewpager2/src/main/java/androidx/viewpager2/widget/ViewPager2.java;l=69) it's haunted with this [bug](https://stackoverflow.com/a/49381907/3678092)

**Comment by troZee** [comment]
> correct me if I'm wrong but since ViewPager2 is based on recyclerview and somehow they decided to make it [final](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:viewpager2/viewpager2/src/main/java/androidx/viewpager2/widget/ViewPager2.java;l=69) it's haunted with this [bug](https://stackoverflow.com/a/49381907/3678092)

it is true, this class is final, but this is not a bug. They decided to do it and they explain it somewhere. Why are you asking ?

**Comment by xfumihiro** [comment]
I'm also trying to use ViewPager2 in RN but hit with the requestLayout bug

**Comment by troZee** [comment]
You can checkout my progress here: https://github.com/react-native-community/react-native-viewpager/commits/%40troZee/viewpager2 . Currently, I am struggling with `FragmentStateAdapter`. Previously I implemented it using pure `RecyclerViewAdapter`, but IMO it is not a good solution. Feel free to share some code, if you would like to.

**Comment by xfumihiro** [comment]
why are you coping VP2 code instead of importing it from stable 1.0.0 release?

**Comment by troZee** [comment]
I almost finished this migration, but I am struggling with `setCurrentItem(args.getInt(0), false)` method. I don't know why it does not work. 

Below you can see what is happening: 
- The background is white, until you swipe a little
- Probably this is related to this https://stackoverflow.com/questions/49371866/recyclerview-wont-update-child-until-i-scroll/49372697#49372697

![gif](https://user-images.githubusercontent.com/12766071/72798659-d7d8b380-3c43-11ea-8ad4-cd691a216200.gif)

**Comment by xfumihiro** [comment]
yep, you have to patch the recycleview with the requestLayout workaround otherwise the children views won't update
