### ISSUE TITLE
TouchableHighlight inside Viewpager taking page-change event as click in ios.

### ISSUE THREAD

**Issue by tusharpandey** [react-native-community/react-native-viewpager#121]
we have used view pager in our app, and there are 3 sections of each and every page , all 3 sections are clickable, for making it clickable we are using TouchableHighlight.

So whenever I am changing my page by swiping. If my touch for sliding is inside TouchableHighlight in IOS it is taking it as click else in android it is working fine.

**Comment by troZee** [comment]
Hey @tusharpandey , Thank you for reporting an issue. Can you tell me, is your issue refers to  https://github.com/react-native-community/react-native-viewpager/issues/73

**Comment by tusharpandey** [comment]
yes... exactly ..... I am also thinking about using this approach and I am sure it will hurt all child components.

**Comment by troZee** [comment]
I would like to keep discussion in one place, hence I close this issue. Please write a comment here https://github.com/react-native-community/react-native-viewpager/issues/73
