### ISSUE TITLE
requireNativeComponent: "RNCViewPager" was not found in the UIManager.

### ISSUE THREAD

**Issue by akashmi** [react-native-community/react-native-viewpager#125]
# Bug

Invariant Violation: Invariant Violation: requireNativeComponent: "RNCViewPager" was not found in the UIManager.

attached screenshot for more details

![Simulator Screen Shot - iPhone X - 2019-12-10 at 13 01 17](https://user-images.githubusercontent.com/11882168/70505207-6f2eef00-1b4d-11ea-950c-092bc38de1da.png)

**Comment by ferrannp** [comment]
You need to link it. The approach changes depending on what React Native version you are: https://github.com/react-native-community/react-native-viewpager#linking.

**Comment by LuckyLuke19** [comment]
I am using React Native 0.61.5 (so the library should be linked automatically) and I still have the same problem. I have followed the custom linking instructions but it was not fixed. What should I do?

**Comment by jalooc** [comment]
Auto linking doesn't work for `>= 0.60`.

**Comment by hpardess** [comment]
![error](https://user-images.githubusercontent.com/6196491/147074123-73a3732d-fc9a-4afe-b30e-f5f63ce200a0.PNG)

I am facing same error and here is my environment:
"react": "17.0.2",
"react-native": "0.66.4",
"react-native-tab-view": "^3.1.1",

I am using following tags but it throws the above error.
<TabView>
            <TabBar></TabBar>
</TabView>
