### ISSUE TITLE
when i use react native navigation createBottomTabNavigator as tabbar viewpager as first tab  then viewpager can not scroll  

### ISSUE THREAD

**Issue by hxyatgithub** [react-native-community/react-native-viewpager#134]
# Bug
viewpager and react navigation conflict on scroll  

## Environment info

react native 0.61.5  navigation 4.0 viewpager3.3

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by troZee** [comment]
This issue is probably related to this [repo](https://github.com/software-mansion/react-native-tab-view-viewpager-adapter)
