### ISSUE TITLE
[iOS] Crash on empty datasource 

### ISSUE THREAD

**Issue by wigleyj** [react-native-community/react-native-viewpager#145]
# Bug
I am trying to render a form with multiple sections. I generate the sections with a map function like so

```
<ViewPager
    style={{flex: 1}}
    initialPage={0}>
{
    this.state.audit.sections.map((section, index) => {
        return (
            <View key={index}>
               <Text>{section.label}</Text>
            </View>
        )
    })
}
</ViewPager>
```

But nothing shows up on iOS. It does show up just fine on android. I have tried manually building the sections like so

```
<ViewPager>
   <View>
      <Text>Hello</Text>
   </View>
   <View>
      <Text>world</Text>
   </View>
</ViewPager>
```
and this show up just fine on both ios and android. it is only when i try to use map on an object on ios i get a blank screen.

## Environment info

React native info output:

```bash
 System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 627.58 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    npm: 6.13.7 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild

```

Library version: 3.3.0

## Steps To Reproduce

1. map over an object to build ViewPager content

Describe what you expected to happen:

1. ViewPager to render

**Comment by troZee** [comment]
Hey,
Thank you for reporting an issue. We are using map function in our example, so you can check this out. It should work fine.

**Comment by TimMun** [comment]
Is your `this.state.audit.sections` ever an empty array? What I realized is that you can never set the ViewPager's children as null - the ViewPager MUST have at least 1 child. If you set with no children, then even if you add some children later on, the children never appear (even though their render functions are called). My workaround is to just put an empty View for a null page. Took me forever to figure out.

**Comment by troZee** [comment]
@TimMun thank you for explanation. I am able to reproduce it on iOS. Android works fine. Below I provide example code to reproduce it

```jsx
this.state = {
  page: 0,
  pages: [],
}

<ViewPager>
  {pages.map(p => this.renderPage(p))}
</ViewPager>
```
