### ISSUE TITLE
[iOS] React Native Navigation 

### ISSUE THREAD

**Issue by jasonkw9** [react-native-community/react-native-viewpager#146]
# Without Viewpager

![](https://user-images.githubusercontent.com/18546855/76378908-aa79cd80-6389-11ea-9250-33a1f00075d2.png)

# With Viewpager

![](https://user-images.githubusercontent.com/18546855/76378922-b2397200-6389-11ea-8cee-c8e0b6b23f67.png)

As shown in the screenshot, after I use the viewpager, my bottom tabs navigation from react native navigation wix has disappear. Anyone has any idea or facing the same issue?

**Comment by skyliwq** [comment]
yes react-native-navigation Version v6 in use react-native-community/viewpager conflict bottomTabs disappear

**Comment by jasonkw9** [comment]
@skyliwq Is there any workaround for this issue? Is this issue with react native navigation or viewpager?

**Comment by troZee** [comment]
Linked issue https://github.com/wix/react-native-navigation/issues/6037

**Comment by troZee** [comment]
> seems like this problem was gone when I updated RNN 6.4.0 and viewpager 3.3.0

In of any problem, please reopen an issue
