### ISSUE TITLE
Feature: Programmatically changing the page

### ISSUE THREAD

**Issue by Deepp0925** [react-native-community/react-native-viewpager#149]
# Feature Request
Based on the given documentation, there is no way to programmatically change pages.

## Why it is needed
For a better UX - swiping 10 times v/s pressing a button once (which is better)

Any kind of help is appreciated

**Comment by troZee** [comment]
This is already implemented. Checkout our example 
https://github.com/react-native-community/react-native-viewpager/blob/master/example/ViewPagerExample.js#L95

**Comment by qasim90** [comment]
This should be documented somewhere so people don't have to dig through code.
