### ISSUE TITLE
Upgraded to React Native 0.62.0 Getting Warning Sign - "Calling `getNode()`

### ISSUE THREAD

**Issue by lucasluca** [react-native-community/react-native-viewpager#157]
ReactNativeFiberHostComponent: Calling `getNode()` on the ref of an Animated component 
is no longer necessary. You can now directly use the ref instead. 
This method will be removed in a future release.

this happend on change tab

**Comment by troZee** [comment]
Hey, I have updated our example to 0.62 and everything works fine. Please checkout our example.

Due above reason, I close this issue.
