### ISSUE TITLE
 Unable to resolve module `UnimplementedView` on IOS

### ISSUE THREAD

**Issue by elizamaria** [react-native-community/react-native-viewpager#16]
Is this a bug report?
Yes

Have you read the Contributing Guidelines?
Yes

Environment:
OS: macOS High Sierra 10.13.3
Node: 8.2.1
npm: 5.3.0
Xcode: 10

Packages:
react: 16.8.3
react-native: 0.59.1

Steps to Reproduce:
Import ViewPager 
Run application on IOS
Getting this error: 
>  Module `UnimplementedView` does not exist in the Haste module map from 'node_modules/@react-native-community/viewpager/js/ViewPagerAndroid.ios.js'

**Comment by danilobuerger** [comment]
Might be related to #7

**Comment by elizamaria** [comment]
It's fixed now. I think it's because of this import fix: https://github.com/react-native-community/react-native-viewpager/pull/8
