### ISSUE TITLE
Failed to resolve: com.github.troZee:ViewPager2:v1.0.6

### ISSUE THREAD

**Issue by bankya** [react-native-community/react-native-viewpager#181]
# Bug report

## Summary
I am trying to upgrade react-native-viewpager from v2.0.2 to v4.0.1. After upgrading and running `yarn install`, I get the following after gradle sync: 

```
Failed to resolve: com.github.troZee:ViewPager2:v1.0.6
Show in Project Structure dialog
Affected Modules: @react-native-community_viewpager
```

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 56.93 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

Library version: x.x.x

## Steps to reproduce

1. Upgrade `@react-native-community/viewpager` in package.json to v4.0.1
2. Run `yarn install`
3. Sync project with gradle files in Android Studio
4. Error: `Failed to resolve: com.github.troZee:ViewPager2:v1.0.6`

Describe what you expected to happen:

1. Upgrade `@react-native-community/viewpager` in package.json to v4.0.1
2. Run `yarn install`
3. Sync project with gradle files in Android Studio
4. Should be able to build the app as expected

**Comment by Decin** [comment]
I also encountered this problem, but  the other day was good.
I think https://github.com/troZee/ViewPager2 which is not in jcenter, Causing "implementation 'com.github.troZee:ViewPager2:v1.0.6'" to fail

**Comment by troZee** [comment]
> I think https://github.com/troZee/ViewPager2 which is not in jcenter,

It is true. This lib is hosted on [jitpack](https://jitpack.io/#troZee/ViewPager2). I have tried to reproduce your issue [here](https://github.com/troZee/viewPagerExample/blob/autolinking/package.json), but it seems to work. 

Are you able to check, if your project contains below line:
```gradle
maven { url 'https://jitpack.io' }
```
it should look like this:
https://github.com/react-native-community/react-native-viewpager/pull/139/files#diff-863402f21446cf9f0f8c358c9eebb8aaR14

**Comment by bankya** [comment]
Oh great, that works perfectly. Though I had to add the `maven { url 'https://jitpack.io' }` under `allprojects` and not `buildscript` . Thank you @troZee
