### ISSUE TITLE
Crash App:  ReactNativePageView.m - Line 382

### ISSUE THREAD

**Issue by mrquanghuy** [react-native-community/react-native-viewpager#187]
# Bug report

**Comment by troZee** [comment]
Please provide more details

**Comment by BohdanRozov** [comment]
@troZee I am not the issue author, but also met this crash in production and there are really lot of crashes with it. Lib version is 4.0.0
![image](https://user-images.githubusercontent.com/29180309/86577553-13153780-bf83-11ea-9479-a5c0a0ff6b46.png)
![image](https://user-images.githubusercontent.com/29180309/86577583-22948080-bf83-11ea-8114-26e6cd941931.png)

**Comment by troZee** [comment]
Hey, 
thank you for providing more context. I think, it will be fixed, once https://github.com/react-native-community/react-native-viewpager/pull/189 merged. After merge, please let me know, how it looks like :D

**Comment by troZee** [comment]
@BohdanRozov can you update VP to 4.1.0 and check, if issue still exist ?
