### ISSUE TITLE
The `RNCViewpager` pod failed to validate due to 1 error:Missing required attribute `homepage`.

### ISSUE THREAD

**Issue by MrLaibin** [react-native-community/react-native-viewpager#19]
my podfiles
`
   pod 'RNCViewpager', :path => "#{RNRootDir}/@react-native-community/viewpager/ios"

`
pod install 
```
[!] The `RNCViewpager` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.
```
vim ./ios/RNCViewpager.podspec
```
  s.homepage     = "https://github.com/react-native-community/react-native-viewpager"
```
pod install ,success!

**Comment by ferrannp** [comment]
Fixed here #21.

**Comment by MrAlekhin** [comment]
sorry, in what version is this fixed? installing `0.60.6` and experiencing that

**Comment by troZee** [comment]
> sorry, in what version is this fixed? installing `0.60.6` and experiencing that

I assume, this is rn version. What version of viewpager do you have ?

**Comment by MrAlekhin** [comment]
@troZee by looking on `package.lock` file my version is `1.1.7` which is used by CI

`"@react-native-community/viewpager": {
      "version": "1.1.7",
      "resolved": "https://registry.npmjs.org/@react-native-community/viewpager/-/viewpager-1.1.7.tgz",
    } `

**Comment by troZee** [comment]
Latest version is 4.0. Please update to at least 3.3.0.
