### ISSUE TITLE
Unable to set the initialPage on ViewPager

### ISSUE THREAD

**Issue by xlf14leena** [react-native-community/react-native-viewpager#190]
The viewpager always seems to default to the first page if I use an iterator to create the child views. If I replace my iterator with the child elements directly like your sample, the initialPage works. I only tested on an android emulator. 
` <ViewPager
        style={styles.viewPager}
        initialPage={3}
        scrollEnabled={true}
        showPageIndicator={true}
        orientation="horizontal"
        transitionStyle="scroll">
        {imagesArray.length > 0 &&
          imagesArray.map((img, index) => {
            return (
              <View key={index}>
                <Text>{index} page</Text>
              </View>
            );
          })}
      </ViewPager>
`

**Comment by troZee** [comment]
Hey, 
Thank you for reporting an issue. I could not reproduce it in example. You can checkout, how view pager works here: 
https://github.com/react-native-community/react-native-viewpager/tree/master/example

**Comment by hengkx** [comment]
android same problem.
I solve
```
        viewPagerRef.current!.setPageWithoutAnimation(idx);

```

**Comment by mikob** [comment]
Seems to only happen on older versions of Android.
