### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException (FragmentStateAdapter.java line 103)

### ISSUE THREAD

**Issue by BohdanRozov** [react-native-community/react-native-viewpager#193]
# Bug report

So far cannot reproduce on my device, but some of app users met this crash. My suggestion is that it is somehow related to lifecycle handling as almost every crash happened in background according to firebase crashlytics

![image](https://user-images.githubusercontent.com/29180309/87020141-2111c500-c1dc-11ea-9db0-76e563f7edc6.png)
![image](https://user-images.githubusercontent.com/29180309/87020190-2e2eb400-c1dc-11ea-84e3-f3c6e6f53948.png)
![image](https://user-images.githubusercontent.com/29180309/87020324-58807180-c1dc-11ea-9c54-bda621080297.png)

**Comment by troZee** [comment]
Previous version (3.3.0) does not cause a crash ? 

Could you provide a code snippet ?

**Comment by troZee** [comment]
Closed in favor fo https://github.com/react-native-community/react-native-viewpager/issues/193
