### ISSUE TITLE
Display only the first page on Android

### ISSUE THREAD

**Issue by WordKuo** [react-native-community/react-native-viewpager#194]
```
             <ViewPager
                ref={viewPager => {
                    this.viewPager = viewPager;
                }}
                initialPage={0}
                onPageScroll={this.onPageScroll}
                onPageSelected={this.onPageSelected}
                style={{ flex: 1, marginTop: -24 / ratio_width}}
            >
                <View key={'GameLiveControllerItemJc'}>
                    <JCEventsListView
                        ref={JCEventsListView => {
                            this.JCEventsListView = JCEventsListView;
                        }}
                        navigator={this.props.navigator}
                    />
                </View>
                <View key={'GameLiveControllerItemBd'}>
                    <BDEventsListView
                        ref={BDEventsListView => {
                            this.BDEventsListView = BDEventsListView;
                        }}
                        navigator={this.props.navigator}
                    />
                </View>
            </ViewPager>
```
**Version: react-native: "0.61.0"**
**Problem: The rest of the entries are not shown, show only the first item**

**Comment by felipeViana** [comment]
have same problem here after some time fiddling with the app.

**Comment by troZee** [comment]
Probably it is related to https://github.com/react-native-community/react-native-viewpager/pull/191 
Can you try the version from master ?
in you `package.json` replace `"@react-native-community/viewpager` with below line:
`"@react-native-community/viewpager": "react-native-community/react-native-viewpager#master",`

Once you do it, please let me know, if it helped.

**Comment by AronBe** [comment]
facing the same issue, on android only the first page is shown

"react-native": "0.63.2",
"@react-native-community/viewpager": "^4.1.6",

`<ViewPager style={styles.viewPager} initialPage={0} showPageIndicator>
      <View
        key={p1.key}
        style={[styles.page, { justifyContent: 'center', marginBottom: 50 }]}
      >
        <Styled.TitleWrapper>
          <Spacing marginBottom={16}>
            <Title>{p1.title}</Title>
          </Spacing>
          <AppText isCentered>{p1.subtitle}</AppText>
        </Styled.TitleWrapper>
      </View>
      {remainingPages.map((page) => (
        <View key={page.key} style={styles.page}>
          <Styled.TitleWrapper>
            <Spacing marginBottom={16}>
              <Title isSmaller>{page.title}</Title>
            </Spacing>
            <AppText isSmaller isCentered>
              {page.subtitle}
            </AppText>
          </Styled.TitleWrapper>
          {page.image && (
            <Spacing marginTop={30} alignCenter>
              <Styled.Image
                source={isDarkMode ? page.image.dark : page.image.light}
              />
            </Spacing>
          )}
        </View>
      ))}
    </ViewPager>`

**Comment by zoftify** [comment]
+1, We're facing the same issue

**Comment by felipeViana** [comment]
#191  fixed it for me

**Comment by troZee** [comment]
Could you check, if 4.1.1 [version](https://github.com/react-native-community/react-native-viewpager/releases/tag/v4.1.1) fixes it ?

**Comment by AronBe** [comment]
@troZee I can confirm that 4.1.1 fixes it !
