### ISSUE TITLE
Could not find com.github.troZee:ViewPager2:v1.0.6.

### ISSUE THREAD

**Issue by leonamjlpaula** [react-native-community/react-native-viewpager#199]
# Bug report

## Summary
After installed via` yarn add` I cannot install app with `npx react-native run-android`. I've tried latest and older versions (4.0.1, 4.0.0).

`error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.troZee:ViewPager2:v1.0.6.
     Searched in the following locations:
       - file:/Users/leonamdepaula/.m2/repository/com/github/troZee/ViewPager2/v1.0.6/ViewPager2-v1.0.6.pom
       - file:/Users/leonamdepaula/.m2/repository/com/github/troZee/ViewPager2/v1.0.6/ViewPager2-v1.0.6.jar
       - file:/Users/leonamdepaula/MEGAsync/SciPet/CrowdPetRN/node_modules/react-native/android/com/github/troZee/ViewPager2/v1.0.6/ViewPager2-v1.0.6.pom
       - file:/Users/leonamdepaula/MEGAsync/SciPet/CrowdPetRN/node_modules/react-native/android/com/github/troZee/ViewPager2/v1.0.6/ViewPager2-v1.0.6.jar
       - file:/Users/leonamdepaula/MEGAsync/SciPet/CrowdPetRN/node_modules/jsc-android/dist/com/github/troZee/ViewPager2/v1.0.6/ViewPager2-v1.0.6.pom
       - file:/Users/leonamdepaula/MEGAsync/SciPet/CrowdPetRN/node_modules/jsc-android/dist/com/github/troZee/ViewPager2/v1.0.6/ViewPager2-v1.0.6.jar
       - https://dl.google.com/dl/android/maven2/com/github/troZee/ViewPager2/v1.0.6/ViewPager2-v1.0.6.pom
       - https://dl.google.com/dl/android/maven2/com/github/troZee/ViewPager2/v1.0.6/ViewPager2-v1.0.6.jar
       - https://jcenter.bintray.com/com/github/troZee/ViewPager2/v1.0.6/ViewPager2-v1.0.6.pom
       - https://jcenter.bintray.com/com/github/troZee/ViewPager2/v1.0.6/ViewPager2-v1.0.6.jar
       - https://sdks.instabug.com/nexus/repository/instabug-cp/com/github/troZee/ViewPager2/v1.0.6/ViewPager2-v1.0.6.pom
       - https://sdks.instabug.com/nexus/repository/instabug-cp/com/github/troZee/ViewPager2/v1.0.6/ViewPager2-v1.0.6.jar
     Required by:
         project :app > project :react-native-community_viewpager`
## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 78.21 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.1, 27.0.3, 28.0.2, 28.0.3
      System Images: android-17 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-N | Intel x86 Atom, android-N | Intel x86 Atom_64
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: x.x.x

## Steps to reproduce

1. …
2. …

Describe what you expected to happen:

1. …
2. …

**Comment by troZee** [comment]
Hey, 
Thank you for reporting an issue. I was trying to reproduce you issue here : https://github.com/troZee/viewPagerExample/commit/71912f8845bf38017610fe7184677f5f5f53a72e

But it seems like everything works fine. You can also try to add below code to `path/to/your/project/example/android/build.gradle`

```
buildscript {
    repositories {
         ....
        maven { url 'https://jitpack.io' }
    }
}

allprojects {
    repositories {
     .......
        maven { url 'https://www.jitpack.io' }
    }
}
```

**Comment by leonamjlpaula** [comment]
> Hey,
> Thank you for reporting an issue. I was trying to reproduce you issue here : [troZee/viewPagerExample@71912f8](https://github.com/troZee/viewPagerExample/commit/71912f8845bf38017610fe7184677f5f5f53a72e)
> 
> But it seems like everything works fine. You can also try to add below code to `path/to/your/project/example/android/build.gradle`
> 
> ```
> buildscript {
>     repositories {
>          ....
>         maven { url 'https://jitpack.io' }
>     }
> }
> 
> allprojects {
>     repositories {
>      .......
>         maven { url 'https://www.jitpack.io' }
>     }
> }
> ```

Thanks a lot! That solved the issue!
