### ISSUE TITLE
android.support.v4.net not exist

### ISSUE THREAD

**Issue by milkcha** [react-native-community/react-native-viewpager#205]
Task :@react-native-community_netinfo:compileDebugJavaWithJavac FAILED
node_modules/@react-native-community/netinfo/android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java:12: error: package android.support.v4.net not exist
import android.support.v4.net.ConnectivityManagerCompat;
                             ^
/node_modules/@react-native-community/netinfo/android/src/main/java/com/reactnativecommunity/netinfo/ConnectivityReceiver.java:154: error: Symbol not found
                    ConnectivityManagerCompat.isActiveNetworkMetered(getConnectivityManager());
                    ^

RN:0.59.3
"@react-native-community/viewpager": "^3.1.0",

**Comment by troZee** [comment]
You need to use `https://github.com/mikehardy/jetifier` to convert androix to support lib. Unless you can use `2.x` version
