### ISSUE TITLE
GetNode() warning on RN 63.2+

### ISSUE THREAD

**Issue by bhirave** [react-native-community/react-native-viewpager#209]
# Bug report

## Summary
Warning appearing: ViewPager: Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release.
 

## Environment info

`react-native info` output:

```bash
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/XXX/.rvm/gems/ruby-2.4.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-24 | ARM 64 v8a, android-24 | ARM EABI v7a, android-24 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_171 - XXXXX
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.10.1 => 4.10.1 
    react: 16.13.1 => 16.13.1 
    react-native: ^0.63.2 => 0.63.2 
```

Library version: 4.1.3

## Steps to reproduce

1. Run the ReactNative app
2. …

Describe what you expected to happen:

1. Warning should not appear

**Comment by troZee** [comment]
Have you tried this solutions ? 

https://github.com/archriss/react-native-snap-carousel/issues/672
https://stackoverflow.com/questions/60910385/upgraded-to-react-native-0-62-0-getting-warning-sign-calling-getnode-on-t

Viewpager does not use `getNode` function, so probably you are using this function inside your code. 

I need more information to be able to reproduce this problem. Please let me know, if above solutions included in links helped you.
