### ISSUE TITLE
Initialization why  onPageScroll is executed after onPageSelected？

### ISSUE THREAD

**Issue by hengkx** [react-native-community/react-native-viewpager#216]
# Question
![image](https://user-images.githubusercontent.com/8358236/90122104-62733280-dd8f-11ea-8e22-5941dcf24b75.png)

**Comment by troZee** [comment]
Probably `onPageSelected` is called on first render of VP, hence you can see it in terminal.

**Comment by hengkx** [comment]
Thank you for your reply. No matter what the situation is, I think it should be like this `onPageScroll` => `onPageSelected`

**Comment by troZee** [comment]
> I think it should be like this onPageScroll => onPageSelected

And it works in that way except the first render.

**Comment by hengkx** [comment]
I need to implement the function of the following code, so there is no way to directly meet it
```
onPageScroll => setDisabled(true)
onPageSelected=>setDisabled(false)
```

**Comment by troZee** [comment]
```js
onPageScroll = (e: PageScrollEvent) => {
  if (e.nativeEvent.offset > 0) {
    setDisabled(true)
  } else {
    setDisabled(false)
  }
```

**Comment by hengkx** [comment]
> ```js
> onPageScroll = (e: PageScrollEvent) => {
>   if (e.nativeEvent.offset > 0) {
>     setDisabled(true)
>   } else {
>     setDisabled(false)
>   }
> ```

@troZee I use version `6.0.0-rc.0`.set `pageMargin={30}` not working.
![image](https://user-images.githubusercontent.com/8358236/125547835-d072b2a4-6383-49ab-806a-150ba0e77460.png)
