### ISSUE TITLE
How to prevent render all component at the same time?

### ISSUE THREAD

**Issue by vinhtran6921** [react-native-community/react-native-viewpager#227]
I had 3 view into Viewpager. every component had call fetch APIs. But it call at the same time when init so it call fetch 5-6 apis. Is there any props for prevent it. Thanks all

**Comment by troZee** [comment]
Lazy load is not currently supported. More you can find here:
https://github.com/react-native-community/react-native-viewpager/issues/104#issuecomment-691431236

**Comment by Rizesocialmedia** [comment]
I controlled the rendering of components based on the current selected index of view pager. 
`        <ViewPager
          style={styles.viewPager}
          overScrollMode={"auto"}
          initialPage={0}
          orientation={"vertical"}
          pageMargin={30}
          onPageSelected={this.onPageSelected}
        >
          {/* {videoModal.map((item, index) => { */}
          {videosList.map((item, index) => {
          {/* {videosList.map((item : IVideoDetails, index) => { */}

          
            return (
              <View key={index} style={styles.container}>
                {
                  (index === selectedIndex) ?
                  <My Component />
                  :
                  <View />
                }

              </View>
            );
          })}
        </ViewPager>`

`  onPageSelected = (e) => {
    this.setState(
      {
        selectedIndex: e.nativeEvent.position,
      })`

**Comment by bygirish** [comment]
I controlled the rendering of components based on the current selected index of view pager. 
`        <ViewPager
          style={styles.viewPager}
          overScrollMode={"auto"}
          initialPage={0}
          orientation={"vertical"}
          pageMargin={30}
          onPageSelected={this.onPageSelected}
        >
          {videosList.map((item, index) => {          
            return (
              <View key={index} style={styles.container}>
                {
                  (index === selectedIndex) ?
                  <My Component />
                  :
                  <View />
                }

              </View>
            );
          })}
        </ViewPager>`

`  onPageSelected = (e) => {
    this.setState(
      {
        selectedIndex: e.nativeEvent.position,
      })`

**Comment by troZee** [comment]
Could you take a look on it: https://github.com/callstack/react-native-pager-view/releases/tag/v6.0.0-rc.0

**Comment by guess** [comment]
@troZee is this going to be released anytime soon?
