### ISSUE TITLE
Error with react-native link

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-viewpager#23]
When I try to run `react-native link @react-native-community/viewpager`

I've got this error:

failed to get dependency config 

@react-native-community/viewpager: ^1.1.6
react-native-cli: 2.0.1
react-native: 0.59.0

**Comment by ferrannp** [comment]
Have you tried it in a new `react-native init` project with react-native `0.59.5`? I just did it again and the linking works for me.

```sh
npx react-native init MyApp
cd MyApp
yarn add @react-native-community/viewpager
react-native link @react-native-community/viewpager
```

Cam you try those steps?

**Comment by sibelius** [comment]
we've got this error on our monorepo setup

https://github.com/entria/entria-fullstack/tree/master/packages/app

**Comment by ferrannp** [comment]
Have you tried linking manually?

**Comment by sibelius** [comment]
manual link works

I want understand why react-native link is showing this error

**Comment by thymikee** [comment]
@sibelius have you tried running with `--projectRoot` flag? I think that may do the trick. We've rewritten that part in v2, but we still need testing in monorepo setups. Looks like we can use Entria for e2e testing, cc @grabbou

**Comment by ferrannp** [comment]
@sibelius not sure what is the status of this but if manual setup works and automatic does not for you, I think this is an issue for https://github.com/react-native-community/cli.
