### ISSUE TITLE
Add iOS support

### ISSUE THREAD

**Issue by ferrannp** [react-native-community/react-native-viewpager#24]
We might like to try and add a wrapper for a native component. Most likely [UIPageViewController](https://developer.apple.com/documentation/uikit/uipageviewcontroller) ?

**Comment by ptrocki** [comment]
@ferrannp I take this ticket. Please assign me to this ticket.

**Comment by saxenanickk** [comment]
@ferrannp I created ViewPager for my React Native project. I provided support for iOS. Shall I make a PR with that code ?

**Comment by ferrannp** [comment]
Hey @saxenanickk, thanks for your interest. However, we have @ptrocki currently working on it in his PR #28. Feel free to jump in to the PR discussion if you like 😃.

**Comment by Noitidart** [comment]
So so awesome! The community is supporting this long forgotten component better than FB! I'm so pleasantly surprised. I was thinking that when components got jettisoned to the community, which has no financial backing, I was thinking the modules/components would turn to rubble. Amazing work folks I really appreciate it!

**Comment by AmeerHamzaRiaz** [comment]
hi, guys any update on this ?

**Comment by ptrocki** [comment]
Almost all android api is covered. There is some bugs, that we want to fix before merge. Feel free to test and comment https://github.com/react-native-community/react-native-viewpager/pull/28

**Comment by ferrannp** [comment]
You can follow the process here: https://github.com/react-native-community/react-native-viewpager/projects/1.

**Comment by tomaszczura** [comment]
Hi guys, do you have any idea when the iOS support might be released?

**Comment by ferrannp** [comment]
DONE!

**Comment by Noitidart** [comment]
Niiiiiice!!!
