### ISSUE TITLE
[Discuss] Obsolete gradle method 

### ISSUE THREAD

**Issue by ptrocki** [react-native-community/react-native-viewpager#29]
# Question
Gradle returns warning:

> WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
> It will be removed at the end of 2019.
> For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
> To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
> Affected Modules: app

This is explanation : https://github.com/facebook/react-native/pull/23103
This is temporary solution: 
https://stackoverflow.com/questions/54420060/warning-api-variant-getmergeassets-is-obsolete-android-studio-3-3

Should we update update react native, to suppress this warning ?

**Comment by ferrannp** [comment]
Seems unrelated to our project. It is just depending on the RN version the consumer is using so I guess we can close it for now as we are gonna be updating this repo anyway.
