### ISSUE TITLE
onPageSelected not working correctly

### ISSUE THREAD

**Issue by SenAlexandru** [react-native-community/react-native-viewpager#33]
My issue is quite basic.
It might be something stupid but i haven't found any solution online anything related to it in the documentation.
I try to use the onPageSelected prop, expecting a number.
`onPageSelected={this.onPageSelected}`
and the method is
`onPageSelected(pageIndex){
        console.log(pageIndex)        
    }` 
The output is a SyntheticEvent, and not a number.

**Comment by ferrannp** [comment]
See the example: https://github.com/react-native-community/react-native-viewpager/blob/master/example/ViewPagerAndroidExample.android.js#L115-L117

```js
  onPageSelected = e => {
    // You can access it by e.nativeEvent.position
  };
```

**Comment by youngjuning** [comment]
why not return index

**Comment by goleary** [comment]
This issue should be reopened until the documentation is updated to reflect this behavior.  I just spent 20 minutes trying to figure out how to use this callback because of the lack of explanation.
