### ISSUE TITLE
How to autoplay

### ISSUE THREAD

**Issue by 13554599576** [react-native-community/react-native-viewpager#35]
# How should I let my pictrue to autoplay? Please, let someone help me.

**Comment by ferrannp** [comment]
There is no such feature. You can probably do it yourself though using something like `setState` to change pages and having a timeout to make it automatically.

**Comment by troZee** [comment]
@leosoares94 
`initialPage`
https://github.com/react-native-community/react-native-viewpager#api
and `setPage` or `setPageWithoutAnimation`
https://github.com/react-native-community/react-native-viewpager/blob/master/example/ViewPagerExample.js#L103
