### ISSUE TITLE
[!] The `RNCOpenDoc` pod failed to validate due to 1 error:

### ISSUE THREAD

**Issue by animaks** [react-native-community/react-native-viewpager#55]
Getting this issue when running 'pod install'

Fetching podspec for `RNCOpenDoc` from `../node_modules/react-native-open-doc/ios`
[!] The `RNCOpenDoc` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is shorter than the summary.

Alternatively, when I am using instead react-native-document-picker I don't get any callback for IOS...

Is there any idea how can upload a document for IOS?

**Comment by ferrannp** [comment]
@animaks I think you are in the wrong repository?
