### ISSUE TITLE
android VIEW_MANAGER_NAME is not correct

### ISSUE THREAD

**Issue by devvit** [react-native-community/react-native-viewpager#66]
# Bug

After v2.0 release, android view manager renamed to "RNCViewPager"

```java
public class ReactViewPagerManager extends ViewGroupManager<ReactViewPager> {

  private static final String REACT_CLASS = "RNCViewPager";

  private static final int COMMAND_SET_PAGE = 1;
  private static final int COMMAND_SET_PAGE_WITHOUT_ANIMATION = 2;
```

but ```ViewPagerAndroid.js``` is still "AndroidViewPager"

```javascript
const VIEW_PAGER_REF = 'viewPager';
const VIEW_MANAGER_NAME = Platform.OS === 'android' ? 'AndroidViewPager' : 'RNCViewPager';
```

```AndroidViewPager``` is legacy code point to [offcial RN](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/viewpager/ReactViewPagerManager.java):

```java
public class ReactViewPagerManager extends ViewGroupManager<ReactViewPager> {

  public static final String REACT_CLASS = "AndroidViewPager";

  public static final int COMMAND_SET_PAGE = 1;
  public static final int COMMAND_SET_PAGE_WITHOUT_ANIMATION = 2;
```

## Steps To Reproduce

Please add a new ```COMMAND_FOO``` like ```COMMAND_SET_PAGE_WITHOUT_ANIMATION```, you cannot pass command through ```receiveCommand```, because the event send to original ```AndroidViewPager```, after change ```ViewPagerAndroid.js```, work correctly.
```javascript
// const VIEW_MANAGER_NAME = Platform.OS === 'android' ? 'AndroidViewPager' : 'RNCViewPager';
const VIEW_MANAGER_NAME = 'RNCViewPager';
```

## Reproducible sample code

**Comment by troZee** [comment]
Hey,
Thank you for reporting issue. The name has been changed as you said here: 
https://github.com/react-native-community/react-native-viewpager/commit/e15966c51558d4a786bea1e2be694aa0988958cb#diff-c274bc79a2ba262fc9467c17dec5c326R29

So probably your change will fix it. Feel free to create PR with solution, that you provided.

**Comment by devvit** [comment]
Well, you responded so quickly. Waiting for #64 and #65 merged, I want to try some new feature :)
