### ISSUE TITLE
mac 错误：程序包 android.support.v4.view不存在

### ISSUE THREAD

**Issue by 1512751361** [react-native-community/react-native-viewpager#74]
# Question
![(N`8~ 1YOL17EWP7I2F%DGB](https://user-images.githubusercontent.com/24776858/66637371-7ae16080-ec45-11e9-86cb-90e825c26c21.png)
![{28B7968B-DC7B-90BD-CE63-9DE29EBDB303}](https://user-images.githubusercontent.com/24776858/66637380-816fd800-ec45-11e9-90b0-10b11d2365e1.jpg)
相同的版本的一个插件？mac和windows拉取的内容怎么不一样呢?
"react": "^16.9.0",
"react-native": "^0.60.5",
 "@react-native-community/viewpager": "^1.1.7",

**Comment by troZee** [comment]
Hey 👋 thank you for reporting this issue. We want to migrate our lib in 3.x.x version. Now jetifier do it for you under the hood.

**Comment by lxy910812** [comment]
> 嘿 👋感谢您报告此问题。我们要迁移3.xx版本的lib。现在，jetifier在引擎盖下为您完成。

什么时候更新啊？RN0.6以上版本都报android.support.v4.view，安卓用不了啊

**Comment by zhuiye** [comment]
the same question ,it occur **android.support.v4.view is not exist**  when gradlew assembleRelease .
in my **gradle.properties**
```
   android.useAndroidX=true
   android.enableJetifier=true
```
**package.json**

```
    "@react-native-community/viewpager": "^2.0.2",
    "react-native": "0.61.4",
```
by the way ,yarn android can work

**Comment by zhuiye** [comment]
run following command can get release apk,
```react-native run-android --variant=release ``
 run **gradlew assembleRelease** and then  was hit   **android.support.v4.view is not exist**

**Comment by zhuiye** [comment]
finally gradlew assembleRelease can gengerate release apk,but i do not know what happen,may be i try install jetifiter?
```
  yarn add -D jetifier
  npx jetify -r
```

**Comment by ferrannp** [comment]
Yes you need jetifier. And `react-native run-android` works because it runs jetifier under the hood.
