### ISSUE TITLE
Cannot find module '@react-native-community\viewpager\package.json'

### ISSUE THREAD

**Issue by hccluck** [react-native-community/react-native-viewpager#82]
Package @react-native-community/viewpager has been ignored because it contains invalid configuration. Reason: Cannot find module '@react-native-community\viewpager\package.json'.
How to deal it

**Comment by troZee** [comment]
Can you provide a reproducible example ?

**Comment by kaank** [comment]
Hi, 

Please remove node_modules, lock files (npm,yarn) and npm install again.
