### ISSUE TITLE
XCode 11 App Launch Crash

### ISSUE THREAD

**Issue by troZee** [react-native-community/react-native-viewpager#85]
# Bug

This bug is described here: https://github.com/facebook/react-native/issues/25154

**Comment by ferrannp** [comment]
I don't think this is relevant to this package.

**Comment by troZee** [comment]
What do you mean ? I applied this solution https://github.com/facebook/react-native/issues/25154#issuecomment-534024991 and it works.

**Comment by troZee** [comment]
This is relevant to example, which uses react-native in v. < 0.59.9
